### PR TITLE
Fix issue #3: merge tarik defined headers with user defined headers

### PR DESCRIPTION
**Pull request by JonathanSudibya**
As defined in title Fix issue #3

### CODE REVIEW

**Comment by diorahman** [comment]
Can we have test on this?

**Comment by JonathanSudibya** [comment]
Right. Will do.

**Comment by JonathanSudibya** [comment]
Can I merge to master and bump version to 1.1.1 @diorahman ?

**Comment by diorahman** [comment]
Published on npm https://www.npmjs.com/package/tarik

**Pull request merged**
